name: CI

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        device: [edge530, edge540, edge830, edge840, edge1030, edge1030plus, edge1040, edge1050, edgeexplore2, edgemtb]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup developer key
      run: |
        echo "${{ secrets.DEVELOPER_KEY }}" | base64 -d > developer_key

    - name: Build for ${{ matrix.device }}
      uses: timangus/garmin-connectiq-build-action@8.2.1
      with:
        device: ${{ matrix.device }}
        developerKey: developer_key
        typeCheck: 3
        outputPath: bin/pinion-garmin-settings-${{ matrix.device }}.prg

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.device }}
        path: bin/pinion-garmin-settings-${{ matrix.device }}.prg
