name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup developer key
      run: |
        echo "${{ secrets.DEVELOPER_KEY }}" | base64 -d > developer_key
    
    - name: Build for edge530
      uses: blackshadev/garmin-connectiq-build-action@8.1.1
      with:
        device: edge530
        developerKey: developer_key
        typeCheck: 3
        outputPath: bin/pinion-garmin-settings.prg
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: bin/pinion-garmin-settings.prg
